CONFIG_GPIO=y
CONFIG_LOG=y
CONFIG_LOG_MODE_IMMEDIATE=y
CONFIG_LOG_DEFAULT_LEVEL=3

CONFIG_SERIAL=y
CONFIG_CONSOLE=y
CONFIG_UART_CONSOLE=y

# System tick
CONFIG_SYS_CLOCK_TICKS_PER_SEC=1000

# Flash support
CONFIG_FLASH=y
CONFIG_FLASH_MAP=y
CONFIG_FLASH_PAGE_LAYOUT=y

# CRC32
CONFIG_CRC=y

# Reboot
CONFIG_REBOOT=y

# MCUboot (adds image header for bootloader)
# 让应用镜像带上 MCUboot 兼容的头部和签名
CONFIG_BOOTLOADER_MCUBOOT=y